### ISSUE TITLE
`mul_assign` not implemented

### ISSUE THREAD

**Issue by DavePearce** [Consensys/corset#163]
In the full traces being checked using the `-N` switch, there is a panic arising:

```
panicked at src/column.rs:132:53:
```

This points to this piece of code:

```rust
pub(crate) fn mul_assign(&mut self, other: &Value) {
        match (self, other) {
            (Value::BigInt(ref mut i1), Value::BigInt(ref i2)) => *i1 *= i2,
            (Value::BigInt(x), Value::Native(y)) => todo!("{} *= {}", x, y), // <---- HERE
            (Value::BigInt(_), Value::ExoNative(_)) => todo!(),
            (Value::Native(_), Value::BigInt(_)) => todo!(),
            (Value::Native(ref mut f1), Value::Native(ref f2)) => f1.mul_assign(f2),
            (Value::Native(_), Value::ExoNative(_)) => todo!(),
            (Value::ExoNative(_), Value::BigInt(_)) => todo!(),
            (Value::ExoNative(_), Value::Native(_)) => todo!(),
            (Value::ExoNative(_), Value::ExoNative(_)) => todo!(),
        }
    }
```

Relevant part of the backtrace:

```
  3: corset::column::Value::mul_assign
             at ./src/column.rs:134:53
   4: corset::check::check_lookup::pseudo_rlc
             at ./src/check.rs:344:13
   5: corset::check::check_lookup
             at ./src/check.rs:389:37
   6: corset::check::check::{{closure}}
             at ./src/check.rs:531:41
```

So, that looks like a `Value::BigInt` is creeping in somehow without being converted to a `Value::Native`.

**Comment by DavePearce** [comment]
There is some interplay with expansion here.  For example, running with `-N` gives the above whilst `-eeeeN` does not.
